
create table if not exists transactions (
  id bigint generated by default as identity primary key,
  student_id text,
  student_name text,
  phone text,
  email text,
  subtotal numeric default 0,
  total numeric default 0,
  payment_status text default 'Pending',
  created_at timestamptz default now()
);

alter table transactions disable row level security;
